import re
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound

def extract_video_id(url: str) -> str:
    """
    Extracts the 11-character video ID from a YouTube URL.
    Supports standard, short (youtu.be), embed, and mobile URLs.
    """
    pattern = r'(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})'
    match = re.search(pattern, url)
    if match:
        return match.group(1)
    raise ValueError("Invalid YouTube URL: Could not extract Video ID")

def load_transcript(video_id: str) -> tuple[list[dict], str]:
    """
    Fetches the transcript list and returns a tuple:
    - list of raw transcript dictionaries (text, start, duration)
    - full concatenated transcript text
    """
    try:
        # Try fetching English transcripts first, fallback to any available
        fetched_transcript = YouTubeTranscriptApi().fetch(video_id, languages=['en', 'en-US'])
        transcript_list = fetched_transcript.to_raw_data()
    except Exception:
        try:
            # Try getting any available transcript (e.g. autogenerated) without language constraint
            fetched_transcript = YouTubeTranscriptApi().fetch(video_id)
            transcript_list = fetched_transcript.to_raw_data()
        except Exception as e:
            raise RuntimeError(f"Could not retrieve transcript for video {video_id}: {str(e)}")

    full_text = " ".join(chunk["text"].replace("\n", " ") for chunk in transcript_list)
    return transcript_list, full_text
